workflows:
  ios-unsigned:
    name: iOS Unsigned APP
    max_build_duration: 120

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod install

      - name: Build iOS without signing
        script: |
          flutter build ios --release --no-codesign

      - name: Create ZIP containing APP only
        script: |
          cd build/ios/iphoneos
          zip -r Dandan.app.zip Runner.app

    artifacts:
      - build/ios/iphoneos/Dandan.app.zip